/* ============================================================================
Proposed Exercise: A common practice in the application of files in embedded systems consists in saving data readings from a sensor, such as temperature for example. With this, you can develop a datalogger that will register the ambient temperature (or of a machine for example) in a known period.
Develop the project of a C program that reads the file "celsius.dat" and shows 10 temperature values in °C on the screen. Then, ask the user to enter 10 new values, updating the file's content. The file must be generated by the program itself when it is run for the first time.

Autor: Eng. André Biasuz
Date:  Jan 2023
============================================================================ */

/* --- Libraries  --- */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* ========================================================================= */
/* --- Constants and Macros --- */

#define FILE_NAME "celsius.dat"
#define NUM_TEMPERATURE_SAMPLES 10
/* ========================================================================= */
/* --- Global variables --- */
/* ========================================================================= */
/* --- Prototypes --- */
FILE *open_file_check_error(char* file_name , char* file_open_id);
FILE *open_file_first_creation_datalogger(char* file_name);
short get_lenght_file(FILE *file);
void log_values_buffer_float (float arr[], int arr_lenght);
void open_and_write_for_array(char* file_name, float arr[], int arr_lenght);

/* ========================================================================= */
/* --- Main routine --- */

int main(int argc, char *argv[])
{    

    FILE *f;
    float ch;
    short i = 1;
    float buffer[NUM_TEMPERATURE_SAMPLES] = {0};
    
    f = open_file_first_creation_datalogger(FILE_NAME);
    f = open_file_check_error(FILE_NAME , "rb");

    short f_lenght = get_lenght_file(f);
    puts("");
    puts("Previous values:");
    puts("");
    do {

        if (f_lenght - ftell(f) == sizeof(ch)) break;
        
        fread(&ch, sizeof(ch), 1, f);
        printf(" Temperature %d: %.2f °C\n", i, ch);
        buffer[i-1] = ch;  
        i++;
        
    } while(!feof(f));
    
    fclose(f);
    puts("");

    log_values_buffer_float(buffer, sizeof(buffer)/sizeof(buffer[0]));
    open_and_write_for_array(FILE_NAME, buffer, sizeof(buffer)/sizeof(buffer[0]));
    puts("New data were stored successfully");
    
    }
/* ========================================================================= */
/* --- Functions' development --- */

FILE *open_file_first_creation_datalogger(char* file_name) {
    
    FILE *f;
    float first_values[NUM_TEMPERATURE_SAMPLES] = {0};
    
    f = fopen(file_name , "rb");
    
    if (f == NULL){
        printf("\nFile not found it will be created\n");
        for (int i = 1 ; i <= (sizeof(first_values)/sizeof(first_values[0])); i++) {
            printf("\nInput temperature %d: ", i);
            scanf("%f", &first_values[i-1]);
        }

        open_and_write_for_array(FILE_NAME, first_values, sizeof(first_values)/sizeof(first_values[0]));
        
        fclose(f);
    } 

    else {
        
        puts("File created already");
        
    }

    return f;
}

FILE *open_file_check_error(char* file_name , char* file_open_id) {
    
    FILE *f;
    
    f = fopen(file_name , file_open_id);
    
    if (f == NULL){
        puts("Error");
        system("pause");
        exit(-1);
    } 

    return f;
    
}

short get_lenght_file(FILE *file) {
    
    fseek(file,0x00,SEEK_END);
    short lenght_of_file = ftell(file);
    fseek(file, 0x00 , SEEK_SET);
    return lenght_of_file;
    
}

void log_values_buffer_float (float arr[], int arr_lenght) {

        char choice;
    
        printf("Would you like to log new values to the logger? Enter Y if so: ");
    
        scanf(" %c", &choice);
        choice = toupper(choice);

        if (choice == 'Y')  {
            for (int i = 0 ; i < arr_lenght; i++) {
                printf("\nInput temperature %d: ", i + 1);
                scanf("%f", &arr[i]);    
        } 
    }
    
}

void open_and_write_for_array(char* file_name, float arr[], int arr_lenght) {
        FILE *f = fopen(file_name , "wb");

        for (int i = 0 ; i <= arr_lenght; i++) {
            fwrite ( &arr[i], 1 , sizeof(float) , f);
        }
        
        fclose(f);
}

/* ========================================================================= */
/* --- End of Program --- */
